spring:
  application:
    name: consul-demo-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        heartbeat:
          enabled: true

server:
  port: 18084

