spring:
  application:
    name: zookeeper-demo-consumer
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
        enabled: true
        prefer-ip-address: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

server:
  port: 19001

